### ISSUE TITLE
Cannot install on Win10

### ISSUE THREAD

**Issue by LastsForever** [melted/hcom#1]
![FF949628E4D89522A7EF604913E19E45](https://user-images.githubusercontent.com/33289453/183571523-9317d40b-abe8-4c11-9d85-d2d91a890d14.png)

**Comment by melted** [comment]
Thanks for the heads up! I have fixed it by replacing the dependency on old-time with time in https://github.com/melted/hcom/commit/d15ca699cec9bc40ad26a93cb428d759ff36f6d0.

**Comment by melted** [comment]
And now it's published on hackage.
